package com.gank.gankly.data.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "READ_HISTORY".
 */
public class ReadHistory {

    private Long id;
    /** Not-null value. */
    private String url;
    private String comment;
    private java.util.Date date;
    private String g_type;

    public ReadHistory() {
    }

    public ReadHistory(Long id) {
        this.id = id;
    }

    public ReadHistory(Long id, String url, String comment, java.util.Date date, String g_type) {
        this.id = id;
        this.url = url;
        this.comment = comment;
        this.date = date;
        this.g_type = g_type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(String url) {
        this.url = url;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public String getG_type() {
        return g_type;
    }

    public void setG_type(String g_type) {
        this.g_type = g_type;
    }

}
