package com.gank.gankly.data;

import android.database.sqlite.SQLiteDatabase;

import com.gank.gankly.data.entity.Customer;
import com.gank.gankly.data.entity.CustomerDao;
import com.gank.gankly.data.entity.Order;
import com.gank.gankly.data.entity.OrderDao;
import com.gank.gankly.data.entity.ReadHistory;
import com.gank.gankly.data.entity.ReadHistoryDao;
import com.gank.gankly.data.entity.UrlCollect;
import com.gank.gankly.data.entity.UrlCollectDao;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig urlCollectDaoConfig;
    private final DaoConfig customerDaoConfig;
    private final DaoConfig orderDaoConfig;
    private final DaoConfig readHistoryDaoConfig;

    private final UrlCollectDao urlCollectDao;
    private final CustomerDao customerDao;
    private final OrderDao orderDao;
    private final ReadHistoryDao readHistoryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        readHistoryDaoConfig = daoConfigMap.get(ReadHistoryDao.class).clone();
        readHistoryDaoConfig.initIdentityScope(type);

        urlCollectDaoConfig = daoConfigMap.get(UrlCollectDao.class).clone();
        urlCollectDaoConfig.initIdentityScope(type);

        customerDaoConfig = daoConfigMap.get(CustomerDao.class).clone();
        customerDaoConfig.initIdentityScope(type);

        orderDaoConfig = daoConfigMap.get(OrderDao.class).clone();
        orderDaoConfig.initIdentityScope(type);

        urlCollectDao = new UrlCollectDao(urlCollectDaoConfig, this);
        customerDao = new CustomerDao(customerDaoConfig, this);
        orderDao = new OrderDao(orderDaoConfig, this);
        readHistoryDao = new ReadHistoryDao(readHistoryDaoConfig, this);

        registerDao(UrlCollect.class, urlCollectDao);
        registerDao(Customer.class, customerDao);
        registerDao(Order.class, orderDao);
        registerDao(ReadHistory.class, readHistoryDao);
    }

    public void clear() {
        urlCollectDaoConfig.getIdentityScope().clear();
        customerDaoConfig.getIdentityScope().clear();
        orderDaoConfig.getIdentityScope().clear();
        readHistoryDaoConfig.getIdentityScope().clear();
    }

    public ReadHistoryDao getReadHistoryDao() {
        return readHistoryDao;
    }

    public UrlCollectDao getUrlCollectDao() {
        return urlCollectDao;
    }

    public CustomerDao getCustomerDao() {
        return customerDao;
    }

    public OrderDao getOrderDao() {
        return orderDao;
    }

}
